package com.hbmax.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "hbmax");

    public static final RegistryObject<CreativeModeTab> RESOURCES_AND_DETAILS_TAB =
            CREATIVE_MODE_TABS.register("resources_and_details_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.resources"))
                            .icon(() -> new ItemStack(ModItems.INGOT_RED_COPPER.get()))
                            .displayItems((parameters, output) -> {
                                output.accept(ModItems.INGOT_RED_COPPER.get());
                                output.accept(ModItems.INGOT_AC227.get());
                                output.accept(ModItems.INGOT_ACTINIUM.get());
                                output.accept(ModItems.INGOT_ADVANCED_ALLOY.get());
                                output.accept(ModItems.INGOT_ALUMINIUM.get());
                                output.accept(ModItems.INGOT_AM241.get());
                                output.accept(ModItems.INGOT_AM242.get());
                                output.accept(ModItems.INGOT_AM_MIX.get());
                                output.accept(ModItems.INGOT_AMERICIUM_FUEL.get());
                                output.accept(ModItems.INGOT_ARSENIC.get());
                                output.accept(ModItems.INGOT_ASBESTOS.get());
                                output.accept(ModItems.INGOT_ACTINIUM.get());
                                output.accept(ModItems.INGOT_ASTATINE.get());
                                output.accept(ModItems.INGOT_AU198.get());
                                output.accept(ModItems.INGOT_AUSTRALIUM.get());
                                output.accept(ModItems.INGOT_BAKELITE.get());
                                output.accept(ModItems.INGOT_BERYLLIUM.get());
                                output.accept(ModItems.INGOT_BIORUBBER.get());
                                output.accept(ModItems.INGOT_BISMUTH.get());
                                output.accept(ModItems.INGOT_BORON.get());
                                output.accept(ModItems.INGOT_BROMINE.get());
                                output.accept(ModItems.INGOT_BSCCO.get());
                                output.accept(ModItems.INGOT_C4.get());
                                output.accept(ModItems.INGOT_CADMIUM.get());
                                output.accept(ModItems.INGOT_CAESIUM.get());
                                output.accept(ModItems.INGOT_CALCIUM.get());
                                output.accept(ModItems.INGOT_CDALLOY.get());
                                output.accept(ModItems.INGOT_CERIUM.get());
                                output.accept(ModItems.INGOT_CHAINSTEEL.get());
                                output.accept(ModItems.INGOT_CHAINSTEEL_HOT.get());
                                output.accept(ModItems.INGOT_CO60.get());
                                output.accept(ModItems.INGOT_COBALT.get());
                                output.accept(ModItems.INGOT_COMBINE_STEEL.get());
                                output.accept(ModItems.INGOT_DAFFERGON.get());
                                output.accept(ModItems.INGOT_DESH.get());
                                output.accept(ModItems.INGOT_DINEUTRONIUM.get());
                                output.accept(ModItems.INGOT_DURA_STEEL.get());
                                output.accept(ModItems.INGOT_ELECTRONIUM.get());
                                output.accept(ModItems.INGOT_EUPHEMIUM.get());
                                output.accept(ModItems.INGOT_FERROURANIUM.get());
                                output.accept(ModItems.INGOT_FIBERGLASS.get());
                                output.accept(ModItems.INGOT_FIREBRICK.get());
                                output.accept(ModItems.INGOT_GH336.get());
                                output.accept(ModItems.INGOT_GRAPHITE.get());
                                output.accept(ModItems.INGOT_HES.get());
                                output.accept(ModItems.INGOT_I131.get());
                                output.accept(ModItems.INGOT_IODINE.get());
                                output.accept(ModItems.INGOT_LANTHANIUM.get());
                                output.accept(ModItems.INGOT_LEAD.get());
                                output.accept(ModItems.INGOT_LES.get());
                                output.accept(ModItems.INGOT_MAGNETIZED_TUNGSTEN.get());
                                output.accept(ModItems.INGOT_METEORITE.get());
                                output.accept(ModItems.INGOT_METEORITE_FORGED.get());
                                output.accept(ModItems.INGOT_METEORITE_FORGED_HOT.get());
                                output.accept(ModItems.INGOT_METEORITE_HOT.get());
                                output.accept(ModItems.BLADE_METEORITE.get());
                                output.accept(ModItems.INGOT_MOX_FUEL.get());
                                output.accept(ModItems.INGOT_MUD.get());
                                output.accept(ModItems.INGOT_NEODYMIUM.get());
                                output.accept(ModItems.INGOT_NEPTUNIUM.get());
                                output.accept(ModItems.INGOT_NEPTUNIUM_FUEL.get());
                                output.accept(ModItems.INGOT_NIOBIUM.get());
                                output.accept(ModItems.INGOT_OSMIRIDIUM.get());
                                output.accept(ModItems.INGOT_PB209.get());
                                output.accept(ModItems.INGOT_PC.get());
                                output.accept(ModItems.INGOT_PHOSPHORUS.get());
                                output.accept(ModItems.INGOT_PLUTONIUM.get());
                                output.accept(ModItems.INGOT_PLUTONIUM_FUEL.get());
                                output.accept(ModItems.INGOT_POLONIUM.get());
                                output.accept(ModItems.INGOT_POLYMER.get());
                                output.accept(ModItems.INGOT_PU238.get());
                                output.accept(ModItems.INGOT_PU239.get());
                                output.accept(ModItems.INGOT_PU240.get());
                                output.accept(ModItems.INGOT_PU241.get());
                                output.accept(ModItems.INGOT_PU_MIX.get());
                                output.accept(ModItems.INGOT_PVC.get());
                                output.accept(ModItems.INGOT_RA226.get());
                                output.accept(ModItems.INGOT_RADSPICE.get());
                                output.accept(ModItems.INGOT_REIIUM.get());
                                output.accept(ModItems.INGOT_RUBBER.get());
                                output.accept(ModItems.INGOT_SATURNITE.get());
                                output.accept(ModItems.INGOT_SCHRABIDATE.get());
                                output.accept(ModItems.INGOT_SCHRABIDIUM.get());
                                output.accept(ModItems.INGOT_SCHRABIDIUM_FUEL.get());
                                output.accept(ModItems.INGOT_SCHRARANIUM.get());
                                output.accept(ModItems.INGOT_SEMTEX.get());
                                output.accept(ModItems.INGOT_SILICON.get());
                                output.accept(ModItems.INGOT_SR90.get());
                                output.accept(ModItems.INGOT_STARMETAL.get());
                                output.accept(ModItems.INGOT_SMORE.get());
                                output.accept(ModItems.INGOT_SOLINIUM.get());
                                output.accept(ModItems.INGOT_STEEL.get());
                                output.accept(ModItems.INGOT_STEEL_DUSTED.get());
                                output.accept(ModItems.INGOT_STEEL_DUSTED_HOT.get());
                                output.accept(ModItems.INGOT_STRONTIUM.get());
                                output.accept(ModItems.INGOT_TANTAlIUM.get());
                                output.accept(ModItems.INGOT_TCALLOY.get());
                                output.accept(ModItems.INGOT_TECHNETIUM.get());
                                output.accept(ModItems.INGOT_TENNESSINE.get());
                                output.accept(ModItems.INGOT_TH232.get());
                                output.accept(ModItems.INGOT_THORIUM_FUEL.get());
                                output.accept(ModItems.INGOT_TITANIUM.get());
                                output.accept(ModItems.INGOT_TUNGSTEN.get());
                                output.accept(ModItems.INGOT_U233.get());
                                output.accept(ModItems.INGOT_U235.get());
                                output.accept(ModItems.INGOT_U238.get());
                                output.accept(ModItems.INGOT_U238M2.get());
                                output.accept(ModItems.INGOT_UNOBTAINIUM.get());
                                output.accept(ModItems.INGOT_URANIUM.get());
                                output.accept(ModItems.INGOT_URANIUM_FUEL.get());
                                output.accept(ModItems.INGOT_VERTICIUM.get());
                                output.accept(ModItems.INGOT_WAIDANIUM.get());
                                output.accept(ModItems.INGOT_ZIRCONIUM.get());

                                output.accept(ModItems.BILLET_AC227.get());
                                output.accept(ModItems.BILLET_AM241.get());
                                output.accept(ModItems.BILLET_AM242.get());
                                output.accept(ModItems.BILLET_AM_MIX.get());
                                output.accept(ModItems.BILLET_AMERICIUM_FUEL.get());
                                output.accept(ModItems.BILLET_AU198.get());
                                output.accept(ModItems.BILLET_AUSTRALIUM.get());
                                output.accept(ModItems.BILLET_AUSTRALIUM_GREATER.get());
                                output.accept(ModItems.BILLET_AUSTRALIUM_LESSER.get());
                                output.accept(ModItems.BILLET_BALEFIRE_GOLD.get());
                                output.accept(ModItems.BILLET_BERYLLIUM.get());
                                output.accept(ModItems.BILLET_BISMUTH.get());
                                output.accept(ModItems.BILLET_CO60.get());
                                output.accept(ModItems.BILLET_FLASHLEAD.get());
                                output.accept(ModItems.BILLET_GH336.get());
                                output.accept(ModItems.BILLET_HES.get());
                                output.accept(ModItems.BILLET_LES.get());
                                output.accept(ModItems.BILLET_MOX_FUEL.get());
                                output.accept(ModItems.BILLET_NEPTUNIUM.get());
                                output.accept(ModItems.BILLET_NEPTUNIUM_FUEL.get());
                                output.accept(ModItems.BILLET_NUCLEAR_WASTE.get());
                                output.accept(ModItems.BILLET_PB209.get());
                                output.accept(ModItems.BILLET_PLUTONIUM.get());
                                output.accept(ModItems.BILLET_PLUTONIUM_FUEL.get());
                                output.accept(ModItems.BILLET_PO210BE.get());
                                output.accept(ModItems.BILLET_POLONIUM.get());
                                output.accept(ModItems.BILLET_PU238.get());
                                output.accept(ModItems.BILLET_PU239.get());
                                output.accept(ModItems.BILLET_PU240.get());
                                output.accept(ModItems.BILLET_PU241.get());
                                output.accept(ModItems.BILLET_PU238BE.get());
                                output.accept(ModItems.BILLET_PU_MIX.get());
                                output.accept(ModItems.BILLET_RA226.get());
                                output.accept(ModItems.BILLET_RA226BE.get());
                                output.accept(ModItems.BILLET_SCHRABIDIUM.get());
                                output.accept(ModItems.BILLET_SCHRABIDIUM_FUEL.get());
                                output.accept(ModItems.BILLET_SILICON.get());
                                output.accept(ModItems.BILLET_SOLINIUM.get());
                                output.accept(ModItems.BILLET_SR90.get());
                                output.accept(ModItems.BILLET_TECHNETIUM.get());
                                output.accept(ModItems.BILLET_TH232.get());
                                output.accept(ModItems.BILLET_THORIUM_FUEL.get());
                                output.accept(ModItems.BILLET_U233.get());
                                output.accept(ModItems.BILLET_U235.get());
                                output.accept(ModItems.BILLET_U238.get());
                                output.accept(ModItems.BILLET_UNOBTAINIUM.get());
                                output.accept(ModItems.BILLET_URANIUM.get());
                                output.accept(ModItems.BILLET_URANIUM_FUEL.get());
                                output.accept(ModItems.BILLET_YHARONITE.get());
                                output.accept(ModItems.BILLET_ZFB_AM_MIX.get());
                                output.accept(ModItems.BILLET_ZFB_BISMUTH.get());
                                output.accept(ModItems.BILLET_ZFB_PU241.get());
                                output.accept(ModItems.BILLET_ZIRCONIUM.get());
                                output.accept(ModItems.BIO_WAFER.get());

                                output.accept(ModItems.NUGGET.get());
                                output.accept(ModItems.NUGGET_AC227.get());
                                output.accept(ModItems.NUGGET_ACTINIUM.get());
                                output.accept(ModItems.NUGGET_AM241.get());
                                output.accept(ModItems.NUGGET_AM242.get());
                                output.accept(ModItems.NUGGET_AM_MIX.get());
                                output.accept(ModItems.NUGGET_AMERICIUM_FUEL.get());
                                output.accept(ModItems.NUGGET_ARSENIC.get());
                                output.accept(ModItems.NUGGET_AU198.get());
                                output.accept(ModItems.NUGGET_AUSTRALIUM.get());
                                output.accept(ModItems.NUGGET_AUSTRALIUM_GREATER.get());
                                output.accept(ModItems.NUGGET_AUSTRALIUM_LESSER.get());
                                output.accept(ModItems.NUGGET_BERYLLIUM.get());
                                output.accept(ModItems.NUGGET_BISMUTH.get());
                                output.accept(ModItems.NUGGET_CADMIUM.get());
                                output.accept(ModItems.NUGGET_CO60.get());
                                output.accept(ModItems.NUGGET_COBALT.get());
                                output.accept(ModItems.NUGGET_DAFFERGON.get());
                                output.accept(ModItems.NUGGET_DESH.get());
                                output.accept(ModItems.NUGGET_DINEUTRONIUM.get());
                                output.accept(ModItems.NUGGET_EUPHEMIUM.get());
                                output.accept(ModItems.NUGGET_GH336.get());
                                output.accept(ModItems.NUGGET_HES.get());
                                output.accept(ModItems.NUGGET_LEAD.get());
                                output.accept(ModItems.NUGGET_LES.get());
                                output.accept(ModItems.NUGGET_MERCURY.get());
                                output.accept(ModItems.NUGGET_MOX_FUEL.get());
                                output.accept(ModItems.NUGGET_NEPTUNIUM.get());
                                output.accept(ModItems.NUGGET_NIOBIUM.get());
                                output.accept(ModItems.NUGGET_OSMIRIDIUM.get());
                                output.accept(ModItems.NUGGET_PB209.get());
                                output.accept(ModItems.NUGGET_PLUTONIUM.get());
                                output.accept(ModItems.NUGGET_PLUTONIUM_FUEL.get());
                                output.accept(ModItems.NUGGET_POLONIUM.get());
                                output.accept(ModItems.NUGGET_PU238.get());
                                output.accept(ModItems.NUGGET_PU239.get());
                                output.accept(ModItems.NUGGET_PU240.get());
                                output.accept(ModItems.NUGGET_PU241.get());
                                output.accept(ModItems.NUGGET_PU_MIX.get());
                                output.accept(ModItems.NUGGET_RA226.get());
                                output.accept(ModItems.NUGGET_RADSPICE.get());
                                output.accept(ModItems.NUGGET_REIIUM.get());
                                output.accept(ModItems.NUGGET_SCHRABIDIUM.get());
                                output.accept(ModItems.NUGGET_SCHRABIDIUM_FUEL.get());
                                output.accept(ModItems.NUGGET_SILICON.get());
                                output.accept(ModItems.NUGGET_SOLINIUM.get());
                                output.accept(ModItems.NUGGET_SR90.get());
                                output.accept(ModItems.NUGGET_STRONTIUM.get());
                                output.accept(ModItems.NUGGET_TANTALIUM.get());
                                output.accept(ModItems.NUGGET_TECHNETIUM.get());
                                output.accept(ModItems.NUGGET_TH232.get());
                                output.accept(ModItems.NUGGET_THORIUM_FUEL.get());
                                output.accept(ModItems.NUGGET_U233.get());
                                output.accept(ModItems.NUGGET_U235.get());
                                output.accept(ModItems.NUGGET_U238.get());
                                output.accept(ModItems.NUGGET_UNOBTAINIUM.get());
                                output.accept(ModItems.NUGGET_UNOBTAINIUM_GREATER.get());
                                output.accept(ModItems.NUGGET_UNOBTANIUM_LESSER.get());
                                output.accept(ModItems.NUGGET_URANIUM.get());
                                output.accept(ModItems.NUGGET_URANIUM_FUEL.get());
                                output.accept(ModItems.NUGGET_VERTICIUM.get());
                                output.accept(ModItems.NUGGET_WEIDANIUM.get());
                                output.accept(ModItems.NUGGET_ZIRCONIUM.get());

                                output.accept(ModItems.POWDER_AC227.get());
                                output.accept(ModItems.POWDER_ACTINIUM.get());
                                output.accept(ModItems.POWDER_ALUMINIUM.get());
                                output.accept(ModItems.POWDER_ASBESTOS.get());
                                output.accept(ModItems.POWDER_ASTATINE.get());
                                output.accept(ModItems.POWDER_AT209.get());
                                output.accept(ModItems.POWDER_AU198.get());
                                output.accept(ModItems.POWDER_AUSTRALIUM.get());
                                output.accept(ModItems.POWDER_BAKELITE.get());
                                output.accept(ModItems.POWDER_BALEFIRE.get());
                                output.accept(ModItems.POWDER_BERYLLIUM.get());
                                output.accept(ModItems.POWDER_BISMUTH.get());
                                output.accept(ModItems.POWDER_BORAX.get());
                                output.accept(ModItems.POWDER_BORON.get());
                                output.accept(ModItems.POWDER_BROMINE.get());
                                output.accept(ModItems.POWDER_CADMIUM.get());
                                output.accept(ModItems.POWDER_CAESIUM.get());
                                output.accept(ModItems.POWDER_CALCIUM.get());
                                output.accept(ModItems.POWDER_CDALLOY.get());
                                output.accept(ModItems.POWDER_CERIUM.get());
                                output.accept(ModItems.POWDER_CHLOROPHYTE.get());
                                output.accept(ModItems.POWDER_CLOUD.get());
                                output.accept(ModItems.POWDER_CO60.get());
                                output.accept(ModItems.POWDER_COAL.get());
                                output.accept(ModItems.POWDER_COBALT.get());
                                output.accept(ModItems.POWDER_COLTAN.get());
                                output.accept(ModItems.POWDER_COMBINE_STEEL.get());
                                output.accept(ModItems.POWDER_COPPER.get());
                                output.accept(ModItems.POWDER_CS137.get());
                                output.accept(ModItems.POWDER_DAFFERGON.get());
                                output.accept(ModItems.POWDER_DESH.get());
                                output.accept(ModItems.POWDER_DESH_MIX.get());
                                output.accept(ModItems.POWDER_DESH_READY.get());
                                output.accept(ModItems.POWDER_DIAMOND.get());
                                output.accept(ModItems.POWDER_DINEUTRONIUM.get());
                                output.accept(ModItems.POWDER_DURA_STEEL.get());
                                output.accept(ModItems.POWDER_EMERALD.get());
                                output.accept(ModItems.POWDER_EUPHEMIUM.get());
                                output.accept(ModItems.POWDER_FIRE.get());
                                output.accept(ModItems.POWDER_FLUX.get());
                                output.accept(ModItems.POWDER_GOLD.get());
                                output.accept(ModItems.POWDER_I131.get());
                                output.accept(ModItems.POWDER_ICE.get());
                                output.accept(ModItems.POWDER_IMPURE_OSMIRIDIUM.get());
                                output.accept(ModItems.POWDER_IODINE.get());
                                output.accept(ModItems.POWDER_IRON.get());
                                output.accept(ModItems.POWDER_LANTHANIUM.get());
                                output.accept(ModItems.POWDER_LAPIS.get());
                                output.accept(ModItems.POWDER_LEAD.get());
                                output.accept(ModItems.POWDER_LIGNITE.get());
                                output.accept(ModItems.POWDER_LITHIUM.get());
                                output.accept(ModItems.POWDER_MAGIC.get());
                                output.accept(ModItems.POWDER_MAGNETIZED_TUNGSTEN.get());
                                output.accept(ModItems.POWDER_METEORITE.get());
                                output.accept(ModItems.POWDER_NEODYMIUM.get());
                                output.accept(ModItems.POWDER_NEPTUNIUM.get());
                                output.accept(ModItems.POWDER_NIOBIUM.get());
                                output.accept(ModItems.POWDER_NITAN_MIX.get());
                                output.accept(ModItems.POWDER_OSMIRIDIUM.get());
                                output.accept(ModItems.POWDER_PALEOGENITE.get());
                                output.accept(ModItems.POWDER_PB209.get());
                                output.accept(ModItems.POWDER_PLUTONIUM.get());
                                output.accept(ModItems.POWDER_POISON.get());
                                output.accept(ModItems.POWDER_POLONIUM.get());
                                output.accept(ModItems.POWDER_POLYMER.get());
                                output.accept(ModItems.POWDER_POWER.get());
                                output.accept(ModItems.POWDER_QUARTZ.get());
                                output.accept(ModItems.POWDER_RA226.get());
                                output.accept(ModItems.POWDER_RADSPICE.get());
                                output.accept(ModItems.POWDER_RED_COPPER.get());
                                output.accept(ModItems.POWDER_REIIUM.get());
                                output.accept(ModItems.POWDER_SCHRABIDATE.get());
                                output.accept(ModItems.POWDER_SCHRABIDIUM.get());
                                output.accept(ModItems.POWDER_SEMTEX_MIX.get());
                                output.accept(ModItems.POWDER_SPARK_MIX.get());
                                output.accept(ModItems.POWDER_SR90.get());
                                output.accept(ModItems.POWDER_STEEL.get());
                                output.accept(ModItems.POWDER_STRONTIUM.get());
                                output.accept(ModItems.POWDER_TANTALIUM.get());
                                output.accept(ModItems.POWDER_TCALLOY.get());
                                output.accept(ModItems.POWDER_TEKTITE.get());
                                output.accept(ModItems.POWDER_TENNESSINE.get());
                                output.accept(ModItems.POWDER_THERMITE.get());
                                output.accept(ModItems.POWDER_THORIUM.get());
                                output.accept(ModItems.POWDER_TITANIUM.get());
                                output.accept(ModItems.POWDER_TUNGSTEN.get());
                                output.accept(ModItems.POWDER_UNOBTAINIUM.get());
                                output.accept(ModItems.POWDER_URANIUM.get());
                                output.accept(ModItems.POWDER_VERTICIUM.get());
                                output.accept(ModItems.POWDER_WEIDANIUM.get());
                                output.accept(ModItems.POWDER_XE135.get());
                                output.accept(ModItems.POWDER_YELLOWCAKE.get());
                                output.accept(ModItems.POWDER_ZIRCONIUM.get());
                                output.accept(ModItems.SULFUR.get());

                                output.accept(ModItems.POWDER_AC227_TINY.get());
                                output.accept(ModItems.POWDER_ACTINIUM_TINY.get());
                                output.accept(ModItems.POWDER_AT209_TINY.get());
                                output.accept(ModItems.POWDER_AU198_TINY.get());
                                output.accept(ModItems.POWDER_BORON_TINY.get());
                                output.accept(ModItems.POWDER_CERIUM_TINY.get());
                                output.accept(ModItems.POWDER_CO60_TINY.get());
                                output.accept(ModItems.POWDER_COAL_TINY.get());
                                output.accept(ModItems.POWDER_COBALT_TINY.get());
                                output.accept(ModItems.POWDER_COLTAN.get());
                                output.accept(ModItems.POWDER_COLTAN_ORE.get());
                                output.accept(ModItems.POWDER_CS137_TINY.get());
                                output.accept(ModItems.POWDER_i131_TINY.get());
                                output.accept(ModItems.POWDER_IODINE_TINY.get());
                                output.accept(ModItems.POWDER_IRON_TINY.get());
                                output.accept(ModItems.POWDER_LANTHANIUM_TINY.get());
                                output.accept(ModItems.POWDER_LITHIUM_TINY.get());
                                output.accept(ModItems.POWDER_METEORITE_TINY.get());
                                output.accept(ModItems.POWDER_NEODYMIUM_TINY.get());
                                output.accept(ModItems.POWDER_NIOBIUM_TINY.get());
                                output.accept(ModItems.POWDER_PALEOGENITE_TINY.get());
                                output.accept(ModItems.POWDER_PB209_TINY.get());
                                output.accept(ModItems.POWDER_RADSPICE_TINY.get());
                                output.accept(ModItems.POWDER_SR90_TINY.get());
                                output.accept(ModItems.POWDER_STEEL_TINY.get());
                                output.accept(ModItems.POWDER_XE135_TINY.get());
                                output.accept(ModItems.NITER.get());

                                output.accept(ModItems.WIRE_TUNGSTEN.get());
                                output.accept(ModItems.WIRE_COPPER.get());
                                output.accept(ModItems.WIRE_ALUMINIUM.get());
                                output.accept(ModItems.WIRE_ADVANCED_ALLOY.get());
                                output.accept(ModItems.WIRE_CARBON.get());
                                output.accept(ModItems.WIRE_GOLD.get());
                                output.accept(ModItems.WIRE_LEAD.get());
                                output.accept(ModItems.WIRE_MAGNETIZED_TUNGSTEN.get());
                                output.accept(ModItems.WIRE_MINGRADE.get());
                                output.accept(ModItems.WIRE_SCHRABIDIUM.get());
                                output.accept(ModItems.WIRE_STEEL.get());
                                output.accept(ModItems.WIRE_DENSE_ADVANCED_ALLOY.get());
                                output.accept(ModItems.WIRE_DENSE_BSCCO.get());
                                output.accept(ModItems.WIRE_DENSE_DINEUTRONIUM.get());
                                output.accept(ModItems.WIRE_DENSE_GOLD.get());
                                output.accept(ModItems.WIRE_DENSE_MAGNETIZED_TUNGSTEN.get());
                                output.accept(ModItems.WIRE_DENSE_NEODYMIUM.get());
                                output.accept(ModItems.WIRE_DENSE_SCHRABIDATE.get());
                                output.accept(ModItems.WIRE_DENSE_SCHRABIDIUM.get());
                                output.accept(ModItems.WIRE_DENSE_STARMETAL.get());
                                output.accept(ModItems.WIRE_DENSE_TUNGSTEN.get());
                                output.accept(ModItems.WIRING_RED_COPPER.get());

                                output.accept(ModItems.PLATE_COPPER.get());
                                output.accept(ModItems.PLATE_POLYMER.get());
                                output.accept(ModItems.PLATE_COPPER.get());
                                output.accept(ModItems.PLATE_ADVANCED_ALLOY.get());
                                output.accept(ModItems.PLATE_ALUMINIUM.get());
                                output.accept(ModItems.PLATE_COMBINE_STEEL.get());
                                output.accept(ModItems.PLATE_DALEKANIUM.get());
                                output.accept(ModItems.PLATE_DESH.get());
                                output.accept(ModItems.PLATE_DINEUTRONIUM.get());
                                output.accept(ModItems.PLATE_EUPHEMIUM.get());
                                output.accept(ModItems.PLATE_GOLD.get());
                                output.accept(ModItems.PLATE_IRON.get());
                                output.accept(ModItems.PLATE_KEVLAR.get());
                                output.accept(ModItems.PLATE_LEAD.get());
                                output.accept(ModItems.PLATE_MIXED.get());
                                output.accept(ModItems.PLATE_PAA.get());
                                output.accept(ModItems.PLATE_SATURNITE.get());
                                output.accept(ModItems.PLATE_SCHRABIDIUM.get());
                                output.accept(ModItems.PLATE_STEEL.get());
                                output.accept(ModItems.PLATE_TITANIUM.get());
                                output.accept(ModItems.PLATE_WELDED_ALUMINIUM.get());
                                output.accept(ModItems.PLATE_WELDED_CDALLOY.get());
                                output.accept(ModItems.PLATE_WELDED_CMBSTEEL.get());
                                output.accept(ModItems.PLATE_WELDED_COPPER.get());
                                output.accept(ModItems.PLATE_WELDED_IRON.get());
                                output.accept(ModItems.PLATE_WELDED_OSMIRIDIUM.get());
                                output.accept(ModItems.PLATE_WELDED_STEEL.get());
                                output.accept(ModItems.PLATE_WELDED_TCALLOY.get());
                                output.accept(ModItems.PLATE_WELDED_TITANIUM.get());
                                output.accept(ModItems.PLATE_WELDED_TUNGSTEN.get());
                                output.accept(ModItems.PLATE_WELDED_ZIRCONIUM.get());
                                output.accept(ModItems.PLATE_CAST_ADVANCED_ALLOY.get());
                                output.accept(ModItems.PLATE_CAST_ALUMINIUM.get());
                                output.accept(ModItems.PLATE_CAST_CDALLOY.get());
                                output.accept(ModItems.PLATE_CAST_CMBSTEEL.get());
                                output.accept(ModItems.PLATE_CAST_COPPER.get());
                                output.accept(ModItems.PLATE_CAST_GOLD.get());
                                output.accept(ModItems.PLATE_CAST_IRON.get());
                                output.accept(ModItems.PLATE_CAST_LEAD.get());
                                output.accept(ModItems.PLATE_CAST_OSMIRIDIUM.get());
                                output.accept(ModItems.PLATE_CAST_SATURNITE.get());
                                output.accept(ModItems.PLATE_CAST_SCHRABIDIUM.get());
                                output.accept(ModItems.PLATE_CAST_STEEL.get());
                                output.accept(ModItems.PLATE_CAST_TCALLOY.get());
                                output.accept(ModItems.PLATE_CAST_TITANIUM.get());
                                output.accept(ModItems.PLATE_CAST_TUNGSTEN.get());
                                output.accept(ModItems.PLATE_CAST_WORKERSALLOY.get());
                                output.accept(ModItems.PLATE_CAST_ZIRCONIUM.get());

                                output.accept(ModItems.COIL_COPPER.get());
                                output.accept(ModItems.COIL_COPPER_TORUS.get());
                                output.accept(ModItems.COIL_ADVANCED_ALLOY.get());
                                output.accept(ModItems.COIL_ADVANCED_TORUS.get());
                                output.accept(ModItems.COIL_GOLD.get());
                                output.accept(ModItems.COIL_GOLD_TORUS.get());
                                output.accept(ModItems.COIL_TUNGSTEN.get());
                                output.accept(ModItems.COIL_MAGNETIZED_TUNGSTEN.get());

                                output.accept(ModItems.COAL_INFERNAL.get());
                                output.accept(ModItems.CINNEBAR.get());

                                output.accept(ModItems.LIGNITE.get());
                                output.accept(ModItems.RARE_EARTH_CHUNK.get());

                                output.accept(ModItems.FRAGMENT_COBALT.get());
                                output.accept(ModItems.FRAGMENT_COLTAN.get());
                                output.accept(ModItems.FRAGMENT_BORON.get());
                                output.accept(ModItems.FRAGMENT_NEODYMIUM.get());
                                output.accept(ModItems.FRAGMENT_NIOBIUM.get());
                                output.accept(ModItems.FRAGMENT_CERIUM.get());
                                output.accept(ModItems.FRAGMENT_LANTHANIUM.get());
                                output.accept(ModItems.FRAGMENT_ACTINIUM.get());

                                output.accept(ModItems.FLUORITE.get());

                                output.accept(ModItems.CIRCUIT_CAPACITOR.get());

                                output.accept(ModItems.BALL_FIRECLAY.get());
                                output.accept(ModItems.BALL_RESIN.get());
                            })
                            .build()
            );

    public static final RegistryObject<CreativeModeTab> ORES_TAB =
            CREATIVE_MODE_TABS.register("ores_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.ores"))
                            .icon(() -> new ItemStack(ModBlocks.URANIUM_ORE.get()))
                            .displayItems((parameters, output) -> {
                                output.accept(ModBlocks.URANIUM_ORE.get());
                                output.accept(ModBlocks.LEAD_ORE.get());
                                output.accept(ModBlocks.TITANIUM_ORE.get());
                                output.accept(ModBlocks.COBALT_ORE.get());
                                output.accept(ModBlocks.ALUMINIUM_ORE.get());
                                output.accept(ModBlocks.ASBESTOS_ORE.get());
                                output.accept(ModBlocks.AUSTRALIUM_ORE.get());
                                output.accept(ModBlocks.CINNEBAR_ORE.get());
                                output.accept(ModBlocks.COAL_OIL_BURNING_ORE.get());
                                output.accept(ModBlocks.COAL_OIL_ORE.get());
                                output.accept(ModBlocks.COLTAN_ORE.get());
                                output.accept(ModBlocks.DAFFERGON_ORE.get());
                                output.accept(ModBlocks.DAFFGON_ORE.get());
                                output.accept(ModBlocks.FLUORITE_ORE.get());
                                output.accept(ModBlocks.LIGNITE_ORE.get());
                                output.accept(ModBlocks.LITHIUM_ORE.get());
                                output.accept(ModBlocks.NITER_ORE.get());
                                output.accept(ModBlocks.RARE_ORE.get());
                                output.accept(ModBlocks.REIIUM_ORE.get());
                                output.accept(ModBlocks.SALPETER_ORE.get());
                                output.accept(ModBlocks.SCHRABIDIUM_ORE.get());
                                output.accept(ModBlocks.SULFUR_ORE.get());
                                output.accept(ModBlocks.THORIUM_ORE.get());
                                output.accept(ModBlocks.TUNGSTEN_ORE.get());
                                output.accept(ModBlocks.UNOBTAINIUM_ORE.get());
                                output.accept(ModBlocks.BEDROCK_BLOCK_ORE.get());
                                output.accept(ModBlocks.BEDROCK_COLTAN_ORE.get());
                                output.accept(ModBlocks.NETHER_COAL_ORE.get());
                                output.accept(ModBlocks.NETHER_COBALT_ORE.get());
                                output.accept(ModBlocks.NETHER_FIRE_ORE.get());
                                output.accept(ModBlocks.NETHER_PLUTONIUM_ORE.get());
                                output.accept(ModBlocks.NETHER_SCHRABIDIUM_ORE.get());
                                output.accept(ModBlocks.NETHER_SMOLDERING_ORE.get());
                                output.accept(ModBlocks.NETHER_SULFUR_ORE.get());
                                output.accept(ModBlocks.NETHER_TUNGSTEN_ORE.get());
                                output.accept(ModBlocks.NETHER_URANIUM_ORE.get());
                                output.accept(ModBlocks.ENDER_TIKITE_ORE.get());
                                output.accept(ModBlocks.ENDER_TIKITE_ALT_ORE.get());
                                output.accept(ModBlocks.VERTICIUM_ORE.get());
                                output.accept(ModBlocks.WAIDANIUM_ORE.get());
                                output.accept(ModBlocks.MALACHITE_ORE.get());
                            })
                            .build()
            );
    // ===== Вкладка механизмов =====
    public static final RegistryObject<CreativeModeTab> MACHINES_TAB =
            CREATIVE_MODE_TABS.register("machines_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.machines"))
                            .icon(() -> new ItemStack(ModBlocks.ELECTRIC_FURNACE.get()))
                            .displayItems((parameters, output) -> {

                                output.accept(ModBlocks.ELECTRIC_FURNACE.get());
                                output.accept(ModBlocks.MACHINE_ARC_FURNACE_OFF.get());
                                output.accept(ModItems.BLAST_FURNACE_ITEM.get());
                                output.accept(ModItems.CABLE.get());
                                output.accept(ModItems.MACHINE_POTATO_BATTERY.get());
                                output.accept(ModItems.MACHINE_BATTERY.get());
                                output.accept(ModItems.MACHINE_LITHIUM_BATTERY.get());
                                output.accept(ModItems.MACHINE_DESH_BATTERY.get());
                                output.accept(ModItems.MACHINE_SATURNITE_BATTERY.get());
                                output.accept(ModItems.MACHINE_SCHRABIDIUM_BATTERY.get());
                                output.accept(ModItems.MACHINE_EUPHEMIUM_BATTERY.get());
                                output.accept(ModItems.MACHINE_RADSPICE_BATTERY.get());
                                output.accept(ModItems.MACHINE_DINEUTRONIUM_BATTERY.get());
                                output.accept(ModItems.MACHINE_ELECTRONIUM_BATTERY.get());
                                output.accept(ModBlocks.MACHINE_TRANSFORMER.get());

                            })
                            .build()
            );
    public static final RegistryObject<CreativeModeTab> TOOLS_TAB =
            CREATIVE_MODE_TABS.register("tools_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.tools"))
                            .icon(() -> new ItemStack(ModItems.MESE_PICKAXE.get()))
                            .displayItems((parameters, output) -> {

                                output.accept(ModItems.TITANIUM_SHOVEL.get());
                                output.accept(ModItems.TITANIUM_PICKAXE.get());
                                output.accept(ModItems.TITANIUM_AXE.get());
                                output.accept(ModItems.TITANIUM_HOE.get());
                                output.accept(ModItems.TITANIUM_SWORD.get());
                                output.accept(ModItems.TITANIUM_HELMET.get());
                                output.accept(ModItems.TITANIUM_PLATE.get());
                                output.accept(ModItems.TITANIUM_LEGS.get());
                                output.accept(ModItems.TITANIUM_BOOTS.get());
                                output.accept(ModItems.STEEL_SHOVEL.get());
                                output.accept(ModItems.STEEL_PICKAXE.get());
                                output.accept(ModItems.STEEL_AXE.get());
                                output.accept(ModItems.STEEL_HOE.get());
                                output.accept(ModItems.STEEL_SWORD.get());
                                output.accept(ModItems.STEEL_HELMET.get());
                                output.accept(ModItems.STEEL_PLATE.get());
                                output.accept(ModItems.STEEL_LEGS.get());
                                output.accept(ModItems.STEEL_BOOTS.get());
                                output.accept(ModItems.ALLOY_SHOVEL.get());
                                output.accept(ModItems.ALLOY_PICKAXE.get());
                                output.accept(ModItems.ALLOY_AXE.get());
                                output.accept(ModItems.ALLOY_HOE.get());
                                output.accept(ModItems.ALLOY_SWORD.get());
                                output.accept(ModItems.ALLOY_HELMET.get());
                                output.accept(ModItems.ALLOY_PLATE.get());
                                output.accept(ModItems.ALLOY_LEGS.get());
                                output.accept(ModItems.ALLOY_BOOTS.get());
                                output.accept(ModItems.DESH_SHOVEL.get());
                                output.accept(ModItems.DESH_PICKAXE.get());
                                output.accept(ModItems.DESH_AXE.get());
                                output.accept(ModItems.DESH_HOE.get());
                                output.accept(ModItems.DESH_SWORD.get());
                                output.accept(ModItems.COBALT_SHOVEL.get());
                                output.accept(ModItems.COBALT_PICKAXE.get());
                                output.accept(ModItems.COBALT_AXE.get());
                                output.accept(ModItems.COBALT_HOE.get());
                                output.accept(ModItems.COBALT_SWORD.get());
                                output.accept(ModItems.COBALT_HELMET.get());
                                output.accept(ModItems.COBALT_PLATE.get());
                                output.accept(ModItems.COBALT_LEGS.get());
                                output.accept(ModItems.COBALT_BOOTS.get());
                                output.accept(ModItems.COBALT_DECORATED_SHOVEL.get());
                                output.accept(ModItems.COBALT_DECORATED_PICKAXE.get());
                                output.accept(ModItems.COBALT_DECORATED_AXE.get());
                                output.accept(ModItems.COBALT_DECORATED_HOE.get());
                                output.accept(ModItems.COBALT_DECORATED_SWORD.get());
                                output.accept(ModItems.STARMETAL_SHOVEL.get());
                                output.accept(ModItems.STARMETAL_PICKAXE.get());
                                output.accept(ModItems.STARMETAL_AXE.get());
                                output.accept(ModItems.STARMETAL_HOE.get());
                                output.accept(ModItems.STARMETAL_SWORD.get());
                                output.accept(ModItems.STARMETAL_HELMET.get());
                                output.accept(ModItems.STARMETAL_PLATE.get());
                                output.accept(ModItems.STARMETAL_LEGS.get());
                                output.accept(ModItems.STARMETAL_BOOTS.get());
                                output.accept(ModItems.CMB_SHOVEL.get());
                                output.accept(ModItems.CMB_PICKAXE.get());
                                output.accept(ModItems.CMB_AXE.get());
                                output.accept(ModItems.CMB_HOE.get());
                                output.accept(ModItems.CMB_SWORD.get());
                                output.accept(ModItems.CMB_HELMET.get());
                                output.accept(ModItems.CMB_PLATE.get());
                                output.accept(ModItems.CMB_LEGS.get());
                                output.accept(ModItems.CMB_BOOTS.get());
                                output.accept(ModItems.BISMUTH_PICKAXE.get());
                                output.accept(ModItems.VOLCANIC_PICKAXE.get());
                                output.accept(ModItems.CHLOROPHYTE_PICKAXE.get());
                                output.accept(ModItems.MESE_PICKAXE.get());
                                output.accept(ModItems.SCHRABIDIUM_SHOVEL.get());
                                output.accept(ModItems.SCHRABIDIUM_PICKAXE.get());
                                output.accept(ModItems.SCHRABIDIUM_AXE.get());
                                output.accept(ModItems.SCHRABIDIUM_HOE.get());
                                output.accept(ModItems.SCHRABIDIUM_SWORD.get());
                                output.accept(ModItems.SCHRABIDIUM_HELMET.get());
                                output.accept(ModItems.SCHRABIDIUM_PLATE.get());
                                output.accept(ModItems.SCHRABIDIUM_LEGS.get());
                                output.accept(ModItems.SCHRABIDIUM_BOOTS.get());

                            })
                            .build()
            );
    public static final RegistryObject<CreativeModeTab> ITEMS_TAB =
            CREATIVE_MODE_TABS.register("items_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.items"))
                            .icon(() -> new ItemStack(ModItems.BATTERY_CREATIVE.get()))
                            .displayItems((parameters, output) -> {

                                output.accept(ModItems.ARC_ELECTRODE.get());
                                output.accept(ModItems.ARC_ELECTRODE_BURNT.get());
                                output.accept(ModItems.ARC_ELECTRODE_DESH.get());

                                output.accept(ModItems.BATTERY_CREATIVE.get());

                                output.accept(ModItems.BATTERY_ADVANCED.get());
                                ItemStack fullAdvanced = new ItemStack(ModItems.BATTERY_ADVANCED.get());
                                fullAdvanced.getOrCreateTag().putInt("charge", 20_000);
                                output.accept(fullAdvanced);
                                output.accept(ModItems.BATTERY_SCHRABIDIUM.get());
                                ItemStack fullSchrabidium = new ItemStack(ModItems.BATTERY_SCHRABIDIUM.get());
                                fullSchrabidium.getOrCreateTag().putInt("charge", 1_000_000);
                                output.accept(fullSchrabidium);
                                output.accept(ModItems.BATTERY.get());
                                ItemStack fullBasic = new ItemStack(ModItems.BATTERY.get());
                                fullBasic.getOrCreateTag().putInt("charge", 5_000);
                                output.accept(fullBasic);
                                output.accept(ModItems.BATTERY_ADVANCED_CELL.get());
                                ItemStack fullAdvancedCell = new ItemStack(ModItems.BATTERY_ADVANCED_CELL.get());
                                fullAdvancedCell.getOrCreateTag().putInt("charge", 60_000);
                                output.accept(fullAdvancedCell);
                                output.accept(ModItems.BATTERY_ADVANCED_CELL_4.get());
                                ItemStack fullAdvancedCell4 = new ItemStack(ModItems.BATTERY_ADVANCED_CELL_4.get());
                                fullAdvancedCell4.getOrCreateTag().putInt("charge", 240_000);
                                output.accept(fullAdvancedCell4);
                                output.accept(ModItems.BATTERY_ADVANCED_CELL_12.get());
                                ItemStack fullAdvancedCell12 = new ItemStack(ModItems.BATTERY_ADVANCED_CELL_12.get());
                                fullAdvancedCell12.getOrCreateTag().putInt("charge", 720_000);
                                output.accept(fullAdvancedCell12);
                                output.accept(ModItems.BATTERY_RED_CELL.get());
                                ItemStack fullRedCell = new ItemStack(ModItems.BATTERY_RED_CELL.get());
                                fullRedCell.getOrCreateTag().putInt("charge", 15_000);
                                output.accept(fullRedCell);
                                output.accept(ModItems.BATTERY_RED_CELL_6.get());
                                ItemStack fullRedCell6 = new ItemStack(ModItems.BATTERY_RED_CELL_6.get());
                                fullRedCell6.getOrCreateTag().putInt("charge", 90_000);
                                output.accept(fullRedCell6);
                                output.accept(ModItems.BATTERY_RED_CELL_24.get());
                                ItemStack fullRedCell24 = new ItemStack(ModItems.BATTERY_RED_CELL_24.get());
                                fullRedCell24.getOrCreateTag().putInt("charge", 360_000);
                                output.accept(fullRedCell24);
                                output.accept(ModItems.BATTERY_LITHIUM.get());
                                ItemStack fullLithium = new ItemStack(ModItems.BATTERY_LITHIUM.get());
                                fullLithium.getOrCreateTag().putInt("charge", 250_000);
                                output.accept(fullLithium);
                                output.accept(ModItems.BATTERY_LITHIUM_CELL.get());
                                ItemStack fullLithiumCell = new ItemStack(ModItems.BATTERY_LITHIUM_CELL.get());
                                fullLithiumCell.getOrCreateTag().putInt("charge", 750_000);
                                output.accept(fullLithiumCell);
                                output.accept(ModItems.BATTERY_LITHIUM_CELL_3.get());
                                ItemStack fullLithiumCell3 = new ItemStack(ModItems.BATTERY_LITHIUM_CELL_3.get());
                                fullLithiumCell3.getOrCreateTag().putInt("charge", 2_250_000);
                                output.accept(fullLithiumCell3);
                                output.accept(ModItems.BATTERY_LITHIUM_CELL_6.get());
                                ItemStack fullLithiumCell6 = new ItemStack(ModItems.BATTERY_LITHIUM_CELL_6.get());
                                fullLithiumCell6.getOrCreateTag().putInt("charge", 4_500_000);
                                output.accept(fullLithiumCell6);
                                output.accept(ModItems.BATTERY_SCHRABIDIUM_CELL.get());
                                ItemStack fullSchrabidiumCell = new ItemStack(ModItems.BATTERY_SCHRABIDIUM_CELL.get());
                                fullSchrabidiumCell.getOrCreateTag().putInt("charge", 3_000_000);
                                output.accept(fullSchrabidiumCell);
                                output.accept(ModItems.BATTERY_SCHRABIDIUM_CELL_2.get());
                                ItemStack fullSchrabidiumCell2 = new ItemStack(ModItems.BATTERY_SCHRABIDIUM_CELL_2.get());
                                fullSchrabidiumCell2.getOrCreateTag().putInt("charge", 6_000_000);
                                output.accept(fullSchrabidiumCell2);
                                output.accept(ModItems.BATTERY_SCHRABIDIUM_CELL_4.get());
                                ItemStack fullSchrabidiumCell4 = new ItemStack(ModItems.BATTERY_SCHRABIDIUM_CELL_4.get());
                                fullSchrabidiumCell4.getOrCreateTag().putInt("charge", 12_000_000);
                                output.accept(fullSchrabidiumCell4);
                                output.accept(ModItems.BATTERY_POTATO.get());
                                ItemStack fullPotato = new ItemStack(ModItems.BATTERY_POTATO.get());
                                fullPotato.getOrCreateTag().putInt("charge", 3_500);
                                output.accept(fullPotato);
                                output.accept(ModItems.BATTERY_POTATOS.get());
                                ItemStack fullPotatos = new ItemStack(ModItems.BATTERY_POTATOS.get());
                                fullPotatos.getOrCreateTag().putInt("charge", 5_000);
                                output.accept(fullPotatos);
                                output.accept(ModItems.BATTERY_SU.get());
                                ItemStack fullSU = new ItemStack(ModItems.BATTERY_SU.get());
                                fullSU.getOrCreateTag().putInt("charge", 100);
                                output.accept(fullSU);
                                output.accept(ModItems.BATTERY_SU_L.get());
                                ItemStack fullSU_L = new ItemStack(ModItems.BATTERY_SU_L.get());
                                fullSU_L.getOrCreateTag().putInt("charge", 3_500);
                                output.accept(fullSU_L);
                                output.accept(ModItems.BATTERY_STEAM.get());
                                ItemStack fullSteam = new ItemStack(ModItems.BATTERY_STEAM.get());
                                fullSteam.getOrCreateTag().putInt("charge", 60_000);
                                output.accept(fullSteam);
                                output.accept(ModItems.BATTERY_STEAM_LARGE.get());
                                ItemStack fullSteamLarge = new ItemStack(ModItems.BATTERY_STEAM_LARGE.get());
                                fullSteamLarge.getOrCreateTag().putInt("charge", 100_000);
                                output.accept(fullSteamLarge);
                                output.accept(ModItems.BATTERY_TRIXITE.get());
                                ItemStack fullTrixite = new ItemStack(ModItems.BATTERY_TRIXITE.get());
                                fullTrixite.getOrCreateTag().putInt("charge", 5_000_000);
                                output.accept(fullTrixite);
                                output.accept(ModItems.BATTERY_SPARK.get());
                                ItemStack fullSpark = new ItemStack(ModItems.BATTERY_SPARK.get());
                                fullSpark.getOrCreateTag().putInt("charge", 100_000_000);
                                output.accept(fullSpark);
                                output.accept(ModItems.BATTERY_SPARK_CELL_6.get());
                                ItemStack fullSparkCell6 = new ItemStack(ModItems.BATTERY_SPARK_CELL_6.get());
                                fullSparkCell6.getOrCreateTag().putInt("charge", 600_000_000);
                                output.accept(fullSparkCell6);
                                output.accept(ModItems.BATTERY_SPARK_CELL_25.get());
                                ItemStack fullSparkCell25 = new ItemStack(ModItems.BATTERY_SPARK_CELL_25.get());
                                fullSparkCell25.getOrCreateTag().putLong("charge", 2_500_000_000L);
                                output.accept(fullSparkCell25);
                                output.accept(ModItems.BATTERY_SPARK_CELL_100.get());
                                ItemStack fullSparkCell100 = new ItemStack(ModItems.BATTERY_SPARK_CELL_100.get());
                                fullSparkCell100.getOrCreateTag().putLong("charge", 10_000_000_000L);
                                output.accept(fullSparkCell100);
                                output.accept(ModItems.BATTERY_SPARK_CELL_1000.get());
                                ItemStack fullSparkCell1000 = new ItemStack(ModItems.BATTERY_SPARK_CELL_1000.get());
                                fullSparkCell1000.getOrCreateTag().putLong("charge", 100_000_000_000L);
                                output.accept(fullSparkCell1000);
                                output.accept(ModItems.BATTERY_SPARK_CELL_2500.get());
                                ItemStack fullSparkCell2500 = new ItemStack(ModItems.BATTERY_SPARK_CELL_2500.get());
                                fullSparkCell2500.getOrCreateTag().putLong("charge", 250_000_000_000L);
                                output.accept(fullSparkCell2500);
                                output.accept(ModItems.BATTERY_SPARK_CELL_10000.get());
                                ItemStack fullSparkCell10000 = new ItemStack(ModItems.BATTERY_SPARK_CELL_10000.get());
                                fullSparkCell10000.getOrCreateTag().putLong("charge", 1_000_000_000_000L);
                                output.accept(fullSparkCell10000);
                                output.accept(ModItems.BATTERY_SPARK_CELL_POWER.get());
                                ItemStack fullSparkCellPower = new ItemStack(ModItems.BATTERY_SPARK_CELL_POWER.get());
                                fullSparkCellPower.getOrCreateTag().putLong("charge", 100_000_000_000_000L);
                                output.accept(fullSparkCellPower);
                                // BatteryGen
                                output.accept(ModItems.BATTERY_SC_URANIUM.get());
                                output.accept(ModItems.BATTERY_SC_TECHNETIUM.get());
                                output.accept(ModItems.BATTERY_SC_PLUTONIUM.get());
                                output.accept(ModItems.BATTERY_SC_POLONIUM.get());
                                output.accept(ModItems.BATTERY_SC_GOLD.get());
                                output.accept(ModItems.BATTERY_SC_LEAD.get());
                                output.accept(ModItems.BATTERY_SC_AMERICIUM.get());
                                output.accept(ModItems.BATTERY_SC_BALEFIRE.get());
                                output.accept(ModItems.BATTERY_SC_SCHRABIDIUM.get());
                                output.accept(ModItems.BATTERY_SC_YHARONITE.get());
                                output.accept(ModItems.BATTERY_SC_ELECTRONIUM.get());

                            })
                            .build()
            );
    public static final RegistryObject<CreativeModeTab> AMMO_TAB =
            CREATIVE_MODE_TABS.register("ammo_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.ammo"))
                            .icon(() -> new ItemStack(ModItems.AMMO_12GAUGE.get()))
                            .displayItems((parameters, output) -> {

                                output.accept(ModItems.GUN_AR15.get());
                                output.accept(ModItems.GUN_REVOLVER.get());
//                                output.accept(ModItems.GUN_AVENGER.get());
//                                output.accept(ModItems.GUN_B92.get());
//                                output.accept(ModItems.GUN_B93.get());
//                                output.accept(ModItems.GUN_BF.get());
//                                output.accept(ModItems.GUN_BOLT_ACTION.get());
//                                output.accept(ModItems.GUN_BOLT_ACTION_GREEN.get());
//                                output.accept(ModItems.GUN_BOLT_ACTION_SATURNITE.get());
//                                output.accept(ModItems.GUN_BOLTER.get());
//                                output.accept(ModItems.GUN_BRIMSTONE.get());
//                                output.accept(ModItems.GUN_CALAMITY.get());
//                                output.accept(ModItems.GUN_CALAMITY_DUAL.get());
//                                output.accept(ModItems.GUN_CRYOLATOR.get());
//                                output.accept(ModItems.GUN_DAMPFMASCHINE.get());
//                                output.accept(ModItems.GUN_DARTER.get());
//                                output.accept(ModItems.GUN_DEAGLE.get());
//                                output.accept(ModItems.GUN_DEFABRICATOR.get());
//                                output.accept(ModItems.GUN_EMP.get());
//                                output.accept(ModItems.GUN_EUTHANASIA.get());
//                                output.accept(ModItems.GUN_FATMAN.get());
//                                output.accept(ModItems.GUN_FLAMER.get());
//                                output.accept(ModItems.GUN_FLECHETTE.get());
//                                output.accept(ModItems.GUN_FOLLY.get());
//                                output.accept(ModItems.GUN_HK69.get());
//                                output.accept(ModItems.GUN_HP.get());
//                                output.accept(ModItems.GUN_IMMOLATOR.get());
//                                output.accept(ModItems.GUN_JACK.get());
//                                output.accept(ModItems.GUN_KARL.get());
                                output.accept(ModItems.GUN_KS23.get());
//                                output.accept(ModItems.GUN_LACUNAE.get());
//                                output.accept(ModItems.GUN_LEVER_ACTION.get());
//                                output.accept(ModItems.GUN_LEVER_ACTION_DARK.get());
//                                output.accept(ModItems.GUN_LEVER_ACTION_SONATA.get());
                                output.accept(ModItems.GUN_MINIGUN.get());
//                                output.accept(ModItems.GUN_MIRV.get());
//                                output.accept(ModItems.GUN_MP.get());
//                                output.accept(ModItems.GUN_MP40.get());
//                                output.accept(ModItems.GUN_OSIPR.get());
//                                output.accept(ModItems.GUN_PANZERSCHRECK.get());
//                                output.accept(ModItems.GUN_PROTO.get());
//                                output.accept(ModItems.GUN_QUADRO.get());
//                                output.accept(ModItems.GUN_REVOLVER_BLACKJACK.get());
//                                output.accept(ModItems.GUN_REVOLVER_CURSED.get());
//                                output.accept(ModItems.GUN_REVOLVER_GOLD.get());
//                                output.accept(ModItems.GUN_REVOLVER_INVERTED.get());
//                                output.accept(ModItems.GUN_REVOLVER_IRON.get());
//                                output.accept(ModItems.GUN_REVOLVER_LEAD.get());
//                                output.accept(ModItems.GUN_REVOLVER_NIGHTMARE.get());
//                                output.accept(ModItems.GUN_REVOLVER_NIGHTMARE2.get());
//                                output.accept(ModItems.GUN_REVOLVER_NOPIP.get());
//                                output.accept(ModItems.GUN_REVOLVER_PIP.get());
//                                output.accept(ModItems.GUN_REVOLVER_RED.get());
//                                output.accept(ModItems.GUN_REVOLVER_SATURNITE.get());
//                                output.accept(ModItems.GUN_REVOLVER_SCHRABIDIUM.get());
//                                output.accept(ModItems.GUN_REVOLVER_SILVER.get());
//                                output.accept(ModItems.GUN_RPG.get());
//                                output.accept(ModItems.GUN_SAUER.get());
//                                output.accept(ModItems.GUN_SKYSTINGER.get());
//                                output.accept(ModItems.GUN_STINGER.get());
//                                output.accept(ModItems.GUN_SPARK.get());
//                                output.accept(ModItems.GUN_SUPER_SHOTGUN.get());
//                                output.accept(ModItems.GUN_SUPERSHOTGUN.get());
                                output.accept(ModItems.GUN_THOMPSON.get());
//                                output.accept(ModItems.GUN_UBOINIK.get());
//                                output.accept(ModItems.GUN_UZI.get());
//                                output.accept(ModItems.GUN_UZI_SILENCER.get());
//                                output.accept(ModItems.GUN_UZI_SATURNITE.get());
//                                output.accept(ModItems.GUN_UZI_SATURNITE_SILENCER.get());
//                                output.accept(ModItems.GUN_VORTEX.get());
//                                output.accept(ModItems.GUN_XVL1456.get());
//                                output.accept(ModItems.GUN_ZOMG.get());
//                                output.accept(ModItems.GUN_EGON.get());
//                                output.accept(ModItems.GUN_CC_PLASMA.get());

                                output.accept(ModItems.GUN_BF_AMMO.get());
                                output.accept(ModItems.GUN_XVL1456_AMMO.get());
                                output.accept(ModItems.GUN_STINGER_AMMO.get());
                                output.accept(ModItems.GUN_SPARK_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_SCHRABIDIUM_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_NIGHTMARE2_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_NIGHTMARE_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_LEAD_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_IRON_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_GOLD_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_CURSED_AMMO.get());
                                output.accept(ModItems.GUN_REVOLVER_AMMO.get());
                                output.accept(ModItems.GUN_OSIPR_AMMO.get());
                                output.accept(ModItems.GUN_OSIPR_AMMO2.get());
                                output.accept(ModItems.GUN_MP_AMMO.get());
                                output.accept(ModItems.GUN_B92_AMMO.get());
                                output.accept(ModItems.GUN_JACK_AMMO.get());
                                output.accept(ModItems.GUN_IMMOLATOR_AMMO.get());
                                output.accept(ModItems.GUN_HP_AMMO.get());
                                output.accept(ModItems.GUN_FLAMER_AMMO.get());
                                output.accept(ModItems.GUN_EUTHANASIA_AMMO.get());
                                output.accept(ModItems.GUN_EMP_AMMO.get());
                                output.accept(ModItems.GUN_DEFABRICATOR_AMMO.get());
                                output.accept(ModItems.GUN_DASH_AMMO.get());

                                output.accept(ModItems.GUN_KIT_1.get());
                                output.accept(ModItems.GUN_KIT_2.get());
                                output.accept(ModItems.GUN_MOIST_NUGGET.get());

                                output.accept(ModItems.AMMO_4GAUGE.get());
                                output.accept(ModItems.AMMO_4GAUGE_BALEFIRE.get());
                                output.accept(ModItems.AMMO_4GAUGE_CANISTER.get());
                                output.accept(ModItems.AMMO_4GAUGE_CLAW.get());
                                output.accept(ModItems.AMMO_4GAUGE_EXPLOSIVE.get());
                                output.accept(ModItems.AMMO_4GAUGE_FLECHETTE.get());
                                output.accept(ModItems.AMMO_4GAUGE_FLECHETTE_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_4GAUGE_KAMPF.get());
                                output.accept(ModItems.AMMO_4GAUGE_SEMTEX.get());
                                output.accept(ModItems.AMMO_4GAUGE_SLEEK.get());
                                output.accept(ModItems.AMMO_4GAUGE_SLUG.get());
                                output.accept(ModItems.AMMO_4GAUGE_VAMPIRE.get());
                                output.accept(ModItems.AMMO_4GAUGE_VOID.get());
                                output.accept(ModItems.AMMO_5MM.get());
                                output.accept(ModItems.AMMO_5MM_DU.get());
                                output.accept(ModItems.AMMO_5MM_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_5MM_EXPLOSIVE.get());
                                output.accept(ModItems.AMMO_5MM_STAR.get());
                                output.accept(ModItems.AMMO_9MM.get());
                                output.accept(ModItems.AMMO_9MM_AP.get());
                                output.accept(ModItems.AMMO_9MM_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_9MM_DU.get());
                                output.accept(ModItems.AMMO_9MM_ROCKET.get());
                                output.accept(ModItems.AMMO_12GAUGE.get());
                                output.accept(ModItems.AMMO_12GAUGE_DU.get());
                                output.accept(ModItems.AMMO_12GAUGE_INCENDIARY.get());
                                output.accept(ModItems.AMMO_12GAUGE_MARAUDER.get());
                                output.accept(ModItems.AMMO_12GAUGE_SHRAPNEL.get());
                                output.accept(ModItems.AMMO_12GAUGE_SLEEK.get());
                                output.accept(ModItems.AMMO_20GAUGE.get());
                                output.accept(ModItems.AMMO_20GAUGE_CAUSTIC.get());
                                output.accept(ModItems.AMMO_20GAUGE_EXPLOSIVE.get());
                                output.accept(ModItems.AMMO_20GAUGE_FLECHETTE.get());
                                output.accept(ModItems.AMMO_20GAUGE_INCENDIARY.get());
                                output.accept(ModItems.AMMO_20GAUGE_SHOCK.get());
                                output.accept(ModItems.AMMO_20GAUGE_SHRAPNEL.get());
                                output.accept(ModItems.AMMO_20GAUGE_SLEEK.get());
                                output.accept(ModItems.AMMO_20GAUGE_SLUG.get());
                                output.accept(ModItems.AMMO_20GAUGE_WITHER.get());
                                output.accept(ModItems.AMMO_22LR.get());
                                output.accept(ModItems.AMMO_22LR_AP.get());
                                output.accept(ModItems.AMMO_22LR_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_44.get());
                                output.accept(ModItems.AMMO_44_AP.get());
                                output.accept(ModItems.AMMO_44_BJ.get());
                                output.accept(ModItems.AMMO_44_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_44_DU.get());
                                output.accept(ModItems.AMMO_44_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_44_PIP.get());
                                output.accept(ModItems.AMMO_44_ROCKET.get());
                                output.accept(ModItems.AMMO_44_SILVER.get());
                                output.accept(ModItems.AMMO_44_STAR.get());
                                output.accept(ModItems.AMMO_50AE.get());
                                output.accept(ModItems.AMMO_50AE_AP.get());
                                output.accept(ModItems.AMMO_50AE_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_50AE_DU.get());
                                output.accept(ModItems.AMMO_50AE_STAR.get());
                                output.accept(ModItems.AMMO_50BMG.get());
                                output.accept(ModItems.AMMO_50BMG_AP.get());
                                output.accept(ModItems.AMMO_50BMG_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_50BMG_DU.get());
                                output.accept(ModItems.AMMO_50BMG_EXPLOSIVE.get());
                                output.accept(ModItems.AMMO_50BMG_FLECHETTE.get());
                                output.accept(ModItems.AMMO_50BMG_FLECHETTE_AM.get());
                                output.accept(ModItems.AMMO_50BMG_FLECHETTE_PO.get());
                                output.accept(ModItems.AMMO_50BMG_INCENDIARY.get());
                                output.accept(ModItems.AMMO_50BMG_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_50BMG_SLEEK.get());
                                output.accept(ModItems.AMMO_50BMG_STAR.get());
                                output.accept(ModItems.AMMO_75BOLT.get());
                                output.accept(ModItems.AMMO_75BOLT_HE.get());
                                output.accept(ModItems.AMMO_75BOLT_INCENDIARY.get());
                                output.accept(ModItems.AMMO_357_DESH.get());
                                output.accept(ModItems.AMMO_556.get());
                                output.accept(ModItems.AMMO_556_AP.get());
                                output.accept(ModItems.AMMO_556_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_556_DU.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE_CHLOROPHYTE.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE_DU.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE_INCENDIARY.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_556_FLECHETTE_SLEEK.get());
                                output.accept(ModItems.AMMO_556_K.get());
                                output.accept(ModItems.AMMO_556_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_556_SLEEK.get());
                                output.accept(ModItems.AMMO_556_STAR.get());
                                output.accept(ModItems.AMMO_556_TRACER.get());
                                output.accept(ModItems.AMMO_CONTAINER.get());
                                output.accept(ModItems.AMMO_DART.get());
                                output.accept(ModItems.AMMO_DGK.get());
                                output.accept(ModItems.AMMO_FOLLY.get());
                                output.accept(ModItems.AMMO_FOLLY_DU.get());
                                output.accept(ModItems.AMMO_FOLLY_NUCLEAR.get());
                                output.accept(ModItems.AMMO_FUEL.get());
                                output.accept(ModItems.AMMO_FUEL_GAS.get());
                                output.accept(ModItems.AMMO_FUEL_NAPALM.get());
                                output.accept(ModItems.AMMO_FUEL_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_FUEL_VAPORIZER.get());
                                output.accept(ModItems.AMMO_GRENADE.get());
                                output.accept(ModItems.AMMO_GRENADE_CONCUSSION.get());
                                output.accept(ModItems.AMMO_GRENADE_FINNED.get());
                                output.accept(ModItems.AMMO_GRENADE_HE.get());
                                output.accept(ModItems.AMMO_GRENADE_INCENDIARY.get());
                                output.accept(ModItems.AMMO_GRENADE_KAMPF.get());
                                output.accept(ModItems.AMMO_GRENADE_NUCLEAR.get());
                                output.accept(ModItems.AMMO_GRENADE_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_GRENADE_SLEEK.get());
                                output.accept(ModItems.AMMO_GRENADE_TOXIC.get());
                                output.accept(ModItems.AMMO_GRENADE_TRACER.get());
                                output.accept(ModItems.AMMO_MIRV.get());
                                output.accept(ModItems.AMMO_MIRV_HIGH.get());
                                output.accept(ModItems.AMMO_MIRV_LOW.get());
                                output.accept(ModItems.AMMO_MIRV_SAFE.get());
                                output.accept(ModItems.AMMO_MIRV_SPECIAL.get());
                                output.accept(ModItems.AMMO_NUKE.get());
                                output.accept(ModItems.AMMO_NUKE_HIGH.get());
                                output.accept(ModItems.AMMO_NUKE_LOW.get());
                                output.accept(ModItems.AMMO_NUKE_PUMPKIN.get());
                                output.accept(ModItems.AMMO_NUKE_SAFE.get());
                                output.accept(ModItems.AMMO_NUKE_TOTS.get());
                                output.accept(ModItems.AMMO_ROCKET.get());
                                output.accept(ModItems.AMMO_ROCKET_CANISTER.get());
                                output.accept(ModItems.AMMO_ROCKET_EMP.get());
                                output.accept(ModItems.AMMO_ROCKET_GLARE.get());
                                output.accept(ModItems.AMMO_ROCKET_HE.get());
                                output.accept(ModItems.AMMO_ROCKET_INCENDIARY.get());
                                output.accept(ModItems.AMMO_ROCKET_NUCLEAR.get());
                                output.accept(ModItems.AMMO_ROCKET_PHOSPHORUS.get());
                                output.accept(ModItems.AMMO_ROCKET_RPC.get());
                                output.accept(ModItems.AMMO_ROCKET_SHRAPNEL.get());
                                output.accept(ModItems.AMMO_ROCKET_SLEEK.get());
                                output.accept(ModItems.AMMO_ROCKET_TOXIC.get());
                                output.accept(ModItems.AMMO_SHELL.get());
                                output.accept(ModItems.AMMO_SHELL_APFSDS_DU.get());
                                output.accept(ModItems.AMMO_SHELL_APFSDS_T.get());
                                output.accept(ModItems.AMMO_SHELL_EXPLOSIVE.get());
                                output.accept(ModItems.AMMO_SHELL_W9.get());

                            })
                            .build()
            );
    public static final RegistryObject<CreativeModeTab> BLOCKS_TAB =
            CREATIVE_MODE_TABS.register("blocks_tab", () ->
                    CreativeModeTab.builder()
                            .title(Component.translatable("itemGroup.hbmax.blocks"))
                            .icon(() -> new ItemStack(ModBlocks.ABSORBER.get()))
                            .displayItems((parameters, output) -> {

                                output.accept(ModBlocks.ASPHALT.get());
                                output.accept(ModBlocks.ABSORBER.get());
                                output.accept(ModBlocks.ABSORBER_GREEN.get());
                                output.accept(ModBlocks.ABSORBER_PINK.get());
                                output.accept(ModBlocks.ABSORBER_RED.get());
                                output.accept(ModBlocks.AMS_BASE.get());
                                output.accept(ModBlocks.AMS_LIMITER.get());
                                output.accept(ModBlocks.AMS_EMITTER.get());
                                output.accept(ModBlocks.ANCIENT_SCRAP.get());
                                output.accept(ModBlocks.ASH_DIGAMMA.get());
                                output.accept(ModBlocks.BALEONITITE_0.get());
                                output.accept(ModBlocks.BALEONITITE_1.get());
                                output.accept(ModBlocks.BALEONITITE_2.get());
                                output.accept(ModBlocks.BALEONITITE_3.get());
                                output.accept(ModBlocks.BALEONITITE_4.get());
                                output.accept(ModBlocks.BALEONITITE_CORE.get());
                                output.accept(ModBlocks.BALEONITITE_SLAKED.get());
                                output.accept(ModBlocks.BARRICADE.get());
                                output.accept(ModBlocks.BASALT.get());
                                output.accept(ModBlocks.BASALT_ASBESTOS.get());
                                output.accept(ModBlocks.BASALT_BRICK.get());
                                output.accept(ModBlocks.BASALT_FLUORITE.get());
                                output.accept(ModBlocks.BASALT_GEM.get());
                                output.accept(ModBlocks.BASALT_POLISHED.get());
                                output.accept(ModBlocks.BASALT_SMOOTH.get());
                                output.accept(ModBlocks.BASALT_SULFUR.get());
                                output.accept(ModBlocks.BASALT_TILES.get());

                                output.accept(ModBlocks.BLAST_DOOR.get());
                                output.accept(ModBlocks.BLOCK_ACTINIUM.get());
                                output.accept(ModBlocks.BLOCK_ADVANCED_ALLOY.get());
                                output.accept(ModBlocks.BLOCK_ALUMINIUM.get());
                                output.accept(ModBlocks.BLOCK_ASBESTOS.get());
                                output.accept(ModBlocks.BLOCK_AU198.get());
                                output.accept(ModBlocks.BLOCK_AUSTRALIUM.get());
                                output.accept(ModBlocks.BLOCK_BAKELITE.get());
                                output.accept(ModBlocks.BLOCK_BERYLLIUM.get());
                                output.accept(ModBlocks.BLOCK_BISMUTH.get());
                                output.accept(ModBlocks.BLOCK_BORON.get());
                                output.accept(ModBlocks.BLOCK_CADMIUM.get());
                                output.accept(ModBlocks.BLOCK_CAP_FRITZ.get());
                                output.accept(ModBlocks.BLOCK_CAP_KORL.get());
                                output.accept(ModBlocks.BLOCK_CAP_NUKA.get());
                                output.accept(ModBlocks.BLOCK_CAP_QUANTUM.get());
                                output.accept(ModBlocks.BLOCK_CAP_RAD.get());
                                output.accept(ModBlocks.BLOCK_CAP_SPARK.get());
                                output.accept(ModBlocks.BLOCK_CAP_STAR.get());
                                output.accept(ModBlocks.BLOCK_CAP_SUNSET.get());
                                output.accept(ModBlocks.BLOCK_COAL_INFERNAL.get());

                                output.accept(ModBlocks.BLOCK_COBALT.get());
                                output.accept(ModBlocks.BLOCK_COKE.get());
                                output.accept(ModBlocks.BLOCK_COLTAN.get());
                                output.accept(ModBlocks.BLOCK_COMBINE_STEEL.get());
                                output.accept(ModBlocks.BLOCK_CORIUM.get());
                                output.accept(ModBlocks.BLOCK_CORIUM_COBBLE.get());
                                output.accept(ModBlocks.BLOCK_DAFFERGON.get());
                                output.accept(ModBlocks.BLOCK_DESH.get());
                                output.accept(ModBlocks.BLOCK_DINEUTRONIUM.get());
                                output.accept(ModBlocks.BLOCK_DURA_STEEL.get());
                                output.accept(ModBlocks.BLOCK_ELECTRICAL_SCRAP.get());
                                output.accept(ModBlocks.BLOCK_EUPHEMIUM.get());
                                output.accept(ModBlocks.BLOCK_EUPHEMIUM_CLUSTER.get());
                                output.accept(ModBlocks.BLOCK_FALLOUT.get());
                                output.accept(ModBlocks.BLOCK_FIBERGLASS.get());
                                output.accept(ModBlocks.BLOCK_FLUORITE.get());
                                output.accept(ModBlocks.BLOCK_FOAM.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE_DRILLED.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE_FUEL.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE_PLUTONIUM.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE_ROD.get());
                                output.accept(ModBlocks.BLOCK_GRAPHITE_SOURCE.get());
                                output.accept(ModBlocks.BLOCK_INSULATOR.get());
                                output.accept(ModBlocks.BLOCK_LANTHANIUM.get());
                                output.accept(ModBlocks.BLOCK_LEAD.get());
                                output.accept(ModBlocks.BLOCK_LIGNITE.get());
                                output.accept(ModBlocks.BLOCK_LITHIUM.get());
                                output.accept(ModBlocks.BLOCK_MAGNETIZED_TUNGSTEN.get());
                                output.accept(ModBlocks.BLOCK_METEOR.get());
                                output.accept(ModBlocks.BLOCK_METEOR_BROKEN.get());
                                output.accept(ModBlocks.BLOCK_METEOR_COBBLE.get());
                                output.accept(ModBlocks.BLOCK_METEOR_MOLTEN.get());
                                output.accept(ModBlocks.BLOCK_METEOR_TREASURE.get());
                                output.accept(ModBlocks.BLOCK_MOX_FUEL.get());
                                output.accept(ModBlocks.BLOCK_NEPTUNIUM.get());
                                output.accept(ModBlocks.BLOCK_NIOBIUM.get());
                                output.accept(ModBlocks.BLOCK_NITER.get());
                                output.accept(ModBlocks.BLOCK_NITER_REINFORCED.get());
                                output.accept(ModBlocks.BLOCK_PLUTONIUM.get());
                                output.accept(ModBlocks.BLOCK_PLUTONIUM_FUEL.get());
                                output.accept(ModBlocks.BLOCK_POLONIUM.get());
                                output.accept(ModBlocks.BLOCK_POLYMER.get());
                                output.accept(ModBlocks.BLOCK_PU238.get());
                                output.accept(ModBlocks.BLOCK_PU239.get());
                                output.accept(ModBlocks.BLOCK_PU240.get());
                                output.accept(ModBlocks.BLOCK_PU_MIX.get());
                                output.accept(ModBlocks.BLOCK_RA226.get());
                                output.accept(ModBlocks.BLOCK_RADSPICE.get());
                                output.accept(ModBlocks.BLOCK_RED_COPPER.get());
                                output.accept(ModBlocks.BLOCK_RED_PHOSPHORUS.get());
                                output.accept(ModBlocks.BLOCK_REIIUM.get());
                                output.accept(ModBlocks.BLOCK_RUBBER.get());
                                output.accept(ModBlocks.BLOCK_SATURNITE.get());
                                output.accept(ModBlocks.BLOCK_SCHRABIDATE.get());
                                output.accept(ModBlocks.BLOCK_SCHRABIDIUM.get());
                                output.accept(ModBlocks.BLOCK_SCHRABIDIUM_CLUSTER.get());
                                output.accept(ModBlocks.BLOCK_SCHRABIDIUM_FUEL.get());
                                output.accept(ModBlocks.BLOCK_SCHRARANIUM.get());
                                output.accept(ModBlocks.BLOCK_SCRAP.get());
                                output.accept(ModBlocks.BLOCK_SEMTEX.get());
                                output.accept(ModBlocks.BLOCK_SLAG.get());
                                output.accept(ModBlocks.BLOCK_SMORE.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL_BF.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL_PRESTO.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL_PRESTO_BF.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL_PRESTO_TRIPLET.get());
                                output.accept(ModBlocks.BLOCK_SOLID_FUEL_PRESTO_TRIPLET_BF.get());
                                output.accept(ModBlocks.BLOCK_SOLINIUM.get());
                                output.accept(ModBlocks.BLOCK_STARMETAL.get());
                                output.accept(ModBlocks.BLOCK_STEEL.get());
                                output.accept(ModBlocks.BLOCK_SULFUR.get());
                                output.accept(ModBlocks.BLOCK_TANTALIUM.get());
                                output.accept(ModBlocks.BLOCK_THORIUM.get());
                                output.accept(ModBlocks.BLOCK_THORIUM_FUEL.get());
                                output.accept(ModBlocks.BLOCK_TITANIUM.get());
                                output.accept(ModBlocks.BLOCK_TRINITITE.get());
                                output.accept(ModBlocks.BLOCK_TRITIUM.get());
                                output.accept(ModBlocks.BLOCK_TUNGSTEN.get());
                                output.accept(ModBlocks.BLOCK_U233.get());
                                output.accept(ModBlocks.BLOCK_U235.get());
                                output.accept(ModBlocks.BLOCK_U238.get());
                                output.accept(ModBlocks.BLOCK_UNOBTAINIUM.get());
                                output.accept(ModBlocks.BLOCK_URANIUM.get());
                                output.accept(ModBlocks.BLOCK_URANIUM_FUEL.get());
                                output.accept(ModBlocks.BLOCK_VERTICIUM.get());
                                output.accept(ModBlocks.BLOCK_WEIDANIUM.get());
                                output.accept(ModBlocks.BLOCK_WHITE_PHOSPHORUS.get());
                                output.accept(ModBlocks.BLOCK_YELLOWCAKE.get());
                                output.accept(ModBlocks.BLOCK_ZIRCONIUM.get());
                            })
                            .build()
            );

    public static void register(IEventBus bus) {
        CREATIVE_MODE_TABS.register(bus);
    }
}

